---
ID: c716a070-a5c1-477b-94c5-2781d48ac769
Parent: 5f8e43a4-506b-4080-962b-503a9a75aac5
Template: e269fbb5-3750-427a-9149-7aa950b49301
Path: /sitecore/templates/Feature/AppDeeplink/_AppDeeplinkSettings/AppDeeplinkSettings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20160117T140859Z
    - ID: 5dd74568-4d4b-44c1-b513-0af5f4cda34f
      # __Created by
      Value: sitecore\admin
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: App deeplink settings
