---
ID: 275c127a-9e78-468d-b0f2-04b8f409a7e0
Parent: c716a070-a5c1-477b-94c5-2781d48ac769
Template: 455a3e98-a627-4b40-8035-e683a0331ac7
Path: /sitecore/templates/Feature/AppDeeplink/_AppDeeplinkSettings/AppDeeplinkSettings/AppDeeplinkSettingsAppName
SharedFields:
- ID: ab162cc0-dc80-4abf-8871-998ee5d7ba32
  # Type
  Value: Single-Line Text
- ID: ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e
  # __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 19a69332-a23e-4e70-8d16-b2640cb24cc8
      # Title
      Value: App name
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      # __Created
      Value: 20160117T140900Z
    - ID: b5e02ad9-d56f-4c41-a065-a133db87bdeb
      # __Display name
      Value: App name
